### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [wrmsr/wava#1]
the webasm is compiled in bytecode?

**Comment by wrmsr** [comment]
I chose to render Java source over direct-to-bytecode compilation to enable higher level tools (specifically debuggers) to understand the emitted code. Being able to single step into the result proved to be worth the cost, and that cost was really only just some perceived notion of not being 'hardcore' or something. Direct bytecode emission definitely has proper uses (presto) but given the necessarily AOT nature of this project I still consider it inappropriate.
